"""
Search Algorithms Module
========================
Implements DFS, BFS, and two A* variants (Manhattan and Euclidean heuristics)
for solving mazes generated by maze_generator.py.

All solvers operate on the full wall/passage grid and return:
    - path:           list of (row, col) grid positions from start to goal
    - nodes_explored: total number of nodes expanded during search
    - max_frontier:   peak size of the frontier/open set during search
"""

import heapq
import math
import time
from typing import List, Tuple, Optional, Dict
from maze_generator import Maze



class SearchResult:
    """Stores the outcome of a search run."""

    def __init__(self, algorithm: str, path: Optional[List[Tuple[int, int]]],
                 nodes_explored: int, max_frontier: int, elapsed_time: float):
        self.algorithm = algorithm
        self.path = path
        self.path_length = len(path) if path else 0
        self.nodes_explored = nodes_explored
        self.max_frontier = max_frontier
        self.elapsed_time = elapsed_time
        self.solved = path is not None

    def __repr__(self):
        return (f"SearchResult(algo={self.algorithm}, solved={self.solved}, "
                f"path_len={self.path_length}, explored={self.nodes_explored}, "
                f"max_frontier={self.max_frontier}, time={self.elapsed_time:.6f}s)")



def _reconstruct_path(parents: Dict, start, goal) -> List[Tuple[int, int]]:
    """Walk backwards from goal to start using the parent dictionary."""
    path = []
    current = goal
    while current is not None:
        path.append(current)
        current = parents.get(current)
    path.reverse()
    return path if path[0] == start else []


# DFS
def dfs(maze: Maze) -> SearchResult:
    """
    Solve the maze using Depth-First Search.

    Uses an explicit stack (iterative) to avoid Python recursion limits
    on large mazes.

    Properties:
        - Not guaranteed to find the shortest path.
        - Memory efficient — O(longest path) frontier size.
        - Time: O(V + E) in the worst case.
    """
    start_time = time.perf_counter()

    start, goal = maze.start, maze.goal
    stack = [start]
    visited = {start}
    parents = {start: None}
    nodes_explored = 0
    max_frontier = 1

    while stack:
        max_frontier = max(max_frontier, len(stack))
        current = stack.pop()
        nodes_explored += 1

        if current == goal:
            elapsed = time.perf_counter() - start_time
            path = _reconstruct_path(parents, start, goal)
            return SearchResult("DFS", path, nodes_explored, max_frontier, elapsed)

        for neighbour in maze.get_neighbours(*current):
            if neighbour not in visited:
                visited.add(neighbour)
                parents[neighbour] = current
                stack.append(neighbour)

    elapsed = time.perf_counter() - start_time
    return SearchResult("DFS", None, nodes_explored, max_frontier, elapsed)

# BFS
def bfs(maze: Maze) -> SearchResult:
    """
    Solve the maze using Breadth-First Search.

    Uses a FIFO queue (collections.deque).

    Properties:
        - Guarantees the shortest path (in terms of number of steps).
        - Higher memory usage than DFS — O(branching_factor^depth).
        - Time: O(V + E).
    """
    from collections import deque
    start_time = time.perf_counter()

    start, goal = maze.start, maze.goal
    queue = deque([start])
    visited = {start}
    parents = {start: None}
    nodes_explored = 0
    max_frontier = 1

    while queue:
        max_frontier = max(max_frontier, len(queue))
        current = queue.popleft()
        nodes_explored += 1

        if current == goal:
            elapsed = time.perf_counter() - start_time
            path = _reconstruct_path(parents, start, goal)
            return SearchResult("BFS", path, nodes_explored, max_frontier, elapsed)

        for neighbour in maze.get_neighbours(*current):
            if neighbour not in visited:
                visited.add(neighbour)
                parents[neighbour] = current
                queue.append(neighbour)

    elapsed = time.perf_counter() - start_time
    return SearchResult("BFS", None, nodes_explored, max_frontier, elapsed)


# A* Search with Manhattan Heuristic
def _manhattan_heuristic(node: Tuple[int, int], goal: Tuple[int, int]) -> int:
    """Manhattan (L1) distance — admissible for grid movement."""
    return abs(node[0] - goal[0]) + abs(node[1] - goal[1])


def astar_manhattan(maze: Maze) -> SearchResult:
    """
    Solve the maze using A* with Manhattan distance heuristic.

    f(n) = g(n) + h(n) where h = Manhattan distance to goal.

    Properties:
        - Optimal and complete (Manhattan is admissible + consistent).
        - Generally explores fewer nodes than BFS.
    """
    start_time = time.perf_counter()

    start, goal = maze.start, maze.goal
    # Priority queue entries: (f_score, tie_breaker, node)
    counter = 0
    open_set = [(0 + _manhattan_heuristic(start, goal), counter, start)]
    g_score = {start: 0}
    parents = {start: None}
    closed_set = set()
    nodes_explored = 0
    max_frontier = 1

    while open_set:
        max_frontier = max(max_frontier, len(open_set))
        _, _, current = heapq.heappop(open_set)

        if current in closed_set:
            continue

        closed_set.add(current)
        nodes_explored += 1

        if current == goal:
            elapsed = time.perf_counter() - start_time
            path = _reconstruct_path(parents, start, goal)
            return SearchResult("A*-Manhattan", path, nodes_explored, max_frontier, elapsed)

        for neighbour in maze.get_neighbours(*current):
            if neighbour in closed_set:
                continue
            tentative_g = g_score[current] + 1  # uniform cost per step

            if tentative_g < g_score.get(neighbour, float('inf')):
                g_score[neighbour] = tentative_g
                f = tentative_g + _manhattan_heuristic(neighbour, goal)
                parents[neighbour] = current
                counter += 1
                heapq.heappush(open_set, (f, counter, neighbour))

    elapsed = time.perf_counter() - start_time
    return SearchResult("A*-Manhattan", None, nodes_explored, max_frontier, elapsed)


# A* Search with Euclidean Heuristic
def _euclidean_heuristic(node: Tuple[int, int], goal: Tuple[int, int]) -> float:
    """Euclidean (L2) distance — admissible but less informed than Manhattan for grids."""
    return math.sqrt((node[0] - goal[0]) ** 2 + (node[1] - goal[1]) ** 2)


def astar_euclidean(maze: Maze) -> SearchResult:
    """
    Solve the maze using A* with Euclidean distance heuristic.

    f(n) = g(n) + h(n) where h = Euclidean distance to goal.

    Properties:
        - Optimal and complete (Euclidean is admissible + consistent).
        - Less informed than Manhattan on 4-connected grids, so typically
          explores more nodes than A*-Manhattan.
    """
    start_time = time.perf_counter()

    start, goal = maze.start, maze.goal
    counter = 0
    open_set = [(0 + _euclidean_heuristic(start, goal), counter, start)]
    g_score = {start: 0}
    parents = {start: None}
    closed_set = set()
    nodes_explored = 0
    max_frontier = 1

    while open_set:
        max_frontier = max(max_frontier, len(open_set))
        _, _, current = heapq.heappop(open_set)

        if current in closed_set:
            continue

        closed_set.add(current)
        nodes_explored += 1

        if current == goal:
            elapsed = time.perf_counter() - start_time
            path = _reconstruct_path(parents, start, goal)
            return SearchResult("A*-Euclidean", path, nodes_explored, max_frontier, elapsed)

        for neighbour in maze.get_neighbours(*current):
            if neighbour in closed_set:
                continue
            tentative_g = g_score[current] + 1

            if tentative_g < g_score.get(neighbour, float('inf')):
                g_score[neighbour] = tentative_g
                f = tentative_g + _euclidean_heuristic(neighbour, goal)
                parents[neighbour] = current
                counter += 1
                heapq.heappush(open_set, (f, counter, neighbour))

    elapsed = time.perf_counter() - start_time
    return SearchResult("A*-Euclidean", None, nodes_explored, max_frontier, elapsed)



def run_all_search(maze: Maze) -> List[SearchResult]:
    """Run all four search algorithms on the given maze and return results."""
    return [dfs(maze), bfs(maze), astar_manhattan(maze), astar_euclidean(maze)]


if __name__ == "__main__":
    m = Maze(10, 10, seed=42)
    print(m)
    print()

    for result in run_all_search(m):
        print(result)
        if result.path:
            m.display(result.path)
            print()
